# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=50, verbose_name='活动名称')),
                ('campaign_type', models.CharField(choices=[('1', '青少儿服务'), ('2', '青年服务'), ('3', '中年服务'), ('4', '长者服务'), ('5', '订餐服务'), ('6', '家政服务'), ('7', '公益服务'), ('8', '公共服务'), ('9', '志愿者服务')], max_length=50, verbose_name='活动分类')),
                ('campaign_date', models.DateTimeField(verbose_name='活动时间')),
                ('campaign_client', models.CharField(max_length=50, verbose_name='服务对象')),
                ('campaign_address', models.CharField(max_length=50, verbose_name='活动地点')),
                ('campaign_content', models.CharField(max_length=255, verbose_name='活动内容')),
                ('campaign_paid', models.CharField(max_length=50, verbose_name='服务费用')),
                ('campaign_signup_deadline', models.DateTimeField(verbose_name='报名截止时间')),
                ('campaign_contact', models.CharField(max_length=50, verbose_name='活动联系方式')),
                ('campaign_counts', models.PositiveSmallIntegerField(verbose_name='可报名总人数')),
            ],
            options={
                'verbose_name_plural': '公益活动发布列表',
            },
        ),
        migrations.CreateModel(
            name='PolicyQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_title', models.CharField(max_length=255, verbose_name='标题')),
                ('qa_content', models.CharField(max_length=255, verbose_name='内容')),
                ('qa_answer', models.CharField(max_length=255, verbose_name='回答')),
                ('qa_ask_date', models.DateTimeField(blank=True, null=True, verbose_name='提问时间')),
                ('qa_answer_date', models.DateTimeField(blank=True, null=True, verbose_name='提问时间')),
            ],
            options={
                'verbose_name_plural': '政策问答',
            },
        ),
        migrations.CreateModel(
            name='ProServ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw_name', models.CharField(max_length=50, verbose_name='社工姓名')),
                ('case_id', models.CharField(max_length=50, verbose_name='个案编号')),
                ('counseling_date', models.DateField(verbose_name='咨询日期')),
                ('proserv_age', models.CharField(blank=True, max_length=20, verbose_name='年龄')),
                ('proserv_jiguan', models.CharField(blank=True, max_length=50, verbose_name='籍贯')),
                ('proserv_house_hold', models.CharField(blank=True, max_length=50, verbose_name='户籍所在地')),
                ('proserv_id_num', models.CharField(blank=True, max_length=50, verbose_name='身份证明')),
                ('proserv_ethnic', models.CharField(blank=True, max_length=50, verbose_name='民族')),
                ('proserv_political_status', models.CharField(blank=True, max_length=50, verbose_name='政治面貌')),
                ('proserv_religion', models.CharField(blank=True, max_length=50, verbose_name='宗教')),
                ('proserv_occupation', models.CharField(blank=True, max_length=50, verbose_name='职业')),
                ('proserv_studying_grade', models.CharField(blank=True, max_length=50, verbose_name='就读年级')),
                ('proserv_degree_of_education', models.CharField(blank=True, max_length=50, verbose_name='文化程度')),
                ('proserv_community', models.CharField(blank=True, max_length=50, verbose_name='所在社区')),
                ('proserv_live_address', models.CharField(blank=True, max_length=50, verbose_name='家庭住址')),
                ('proserv_married', models.CharField(blank=True, choices=[('1', '单身'), ('2', '同居'), ('3', '已婚'), ('4', '分居'), ('5', '离婚'), ('6', '丧偶'), ('7', '其它')], max_length=1, verbose_name='婚姻状况')),
                ('proserv_counseling', models.CharField(blank=True, choices=[('1', '亲子关系问题'), ('2', '婚姻问题'), ('3', '家庭纠纷'), ('4', '经济问题'), ('5', '职业问题'), ('6', '住屋问题'), ('7', '家庭暴力致伤/死(受害对象: 子女 / 配偶 / 老人 / 其它______)'), ('8', '个人精神/情绪问题'), ('9', '个人行为问题(吸毒/酒/赌博)'), ('10', '恋爱/交友问题'), ('11', '患病/复康问题(病类)'), ('12', '未婚怀孕'), ('13', '收养'), ('14', '其它')], max_length=50, verbose_name='咨询问题')),
                ('social_assistance', models.CharField(blank=True, choices=[('1', '医疗救助'), ('2', '教育救助'), ('3', '住房救助'), ('4', '临时救助'), ('5', '最低生活保障救助'), ('6', '其它')], max_length=1, verbose_name='社会救助')),
                ('counseling_results', models.CharField(blank=True, choices=[('1', '问题改善/解决结案'), ('2', '转为辅导个案'), ('3', '转介')], max_length=1, verbose_name='咨询结果')),
            ],
            options={
                'verbose_name_plural': '专业服务登记列表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('cellphone', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('user_sex', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别')),
                ('user_city', models.CharField(blank=True, max_length=10, verbose_name='城市')),
                ('user_country', models.CharField(blank=True, max_length=10, verbose_name='国家')),
                ('user_province', models.CharField(blank=True, max_length=10, verbose_name='省份')),
                ('user_language', models.CharField(default='zh_CN', max_length=10, verbose_name='语言')),
                ('user_subscribe_time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='关注公众号时间')),
                ('user_access_token', models.CharField(max_length=255)),
                ('user_access_time', models.DateTimeField(blank=True, null=True)),
                ('user_refresh_token', models.CharField(max_length=255)),
                ('user_refresh_time', models.DateTimeField(blank=True, null=True)),
                ('user_volunteer_or_not', models.BooleanField(default=False, verbose_name='是否志愿者')),
            ],
            options={
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='VolServ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volserv_title', models.CharField(max_length=100, verbose_name='服务主题')),
                ('volserv_content', models.CharField(max_length=200, verbose_name='服务内容')),
                ('volserv_client', models.CharField(max_length=100, verbose_name='服务对象')),
                ('volserv_date', models.DateTimeField(verbose_name='服务时间')),
                ('volserv_address', models.CharField(max_length=100, verbose_name='服务地址')),
                ('volserv_signup_deadline', models.DateField(verbose_name='服务报名截止时间')),
                ('volserv_contact', models.CharField(max_length=100, verbose_name='服务联系方式')),
                ('volserv_counts', models.PositiveSmallIntegerField(verbose_name='可报名人数')),
            ],
            options={
                'verbose_name_plural': '志愿者服务清单',
            },
        ),
        migrations.CreateModel(
            name='VolTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltraining_zhu_jiang_ren', models.CharField(max_length=50, verbose_name='主讲人')),
                ('voltraining_theme', models.CharField(max_length=100, verbose_name='培训主题')),
                ('voltraining_date', models.DateTimeField(verbose_name='培训时间')),
                ('voltraining_content', models.CharField(max_length=100, verbose_name='培训内容')),
                ('voltraining_address', models.CharField(max_length=100, verbose_name='培训地址')),
                ('voltraining_counts', models.PositiveSmallIntegerField(verbose_name='可报名人数')),
                ('voltraining_sign_up_deadline', models.DateField(verbose_name='服务报名截止时间')),
            ],
            options={
                'verbose_name_plural': '志愿者培训清单',
            },
        ),
        migrations.CreateModel(
            name='VolunteerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volinfo_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('volinfo_sex', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别')),
                ('volinfo_age', models.CharField(blank=True, max_length=2, verbose_name='年龄')),
                ('volinfo_jiguan', models.CharField(blank=True, max_length=100, verbose_name='籍贯')),
                ('volinfo_live_address', models.CharField(blank=True, max_length=100, verbose_name='住址')),
                ('volinfo_married', models.CharField(blank=True, choices=[('1', '单身'), ('2', '同居'), ('3', '已婚'), ('4', '分居'), ('5', '离婚'), ('6', '丧偶'), ('7', '其它')], max_length=1, verbose_name='婚姻状况')),
                ('volinfo_idcard_type', models.CharField(blank=True, choices=[('1', '身份证'), ('2', '护照'), ('3', '警官证'), ('4', '军官证')], default='1', max_length=10, verbose_name='证件类型')),
                ('volinfo_id_num', models.CharField(blank=True, max_length=18, verbose_name='证件号码')),
                ('volinfo_birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('volinfo_email', models.CharField(blank=True, max_length=50, verbose_name='电子邮箱')),
                ('volinfo_graduate_school', models.CharField(blank=True, max_length=50, verbose_name='毕业院校')),
                ('volinfo_graduate_date', models.DateField(blank=True, null=True, verbose_name='毕业时间')),
                ('volinfo_education', models.CharField(blank=True, max_length=5, verbose_name='学历')),
                ('volinfo_profession', models.CharField(blank=True, max_length=50, verbose_name='专业')),
                ('volinfo_employer', models.CharField(blank=True, max_length=50, verbose_name='工作单位')),
                ('volinfo_position', models.CharField(blank=True, max_length=50, verbose_name='职务')),
                ('volinfo_mail_address', models.CharField(blank=True, max_length=50, verbose_name='通讯地址')),
                ('volinfo_zipcode', models.CharField(blank=True, max_length=10, verbose_name='邮编')),
                ('volinfo_contact_number', models.CharField(blank=True, max_length=50, verbose_name='固定电话')),
                ('volinfo_cell_number', models.CharField(max_length=11, verbose_name='移动电话')),
                ('volinfo_service_area', models.CharField(blank=True, max_length=50, verbose_name='志愿服务区')),
                ('volinfo_service_date', models.CharField(choices=[('1', '法定休息日'), ('2', '工作日'), ('3', '不限')], max_length=50, verbose_name='志愿服务时间')),
                ('volinfo_skills', models.CharField(blank=True, max_length=50, verbose_name='技能')),
                ('volinfo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='微信用户')),
            ],
            options={
                'verbose_name_plural': '志愿者信息',
            },
        ),
        migrations.AddField(
            model_name='voltraining',
            name='signup_user_list',
            field=models.ManyToManyField(blank=True, to='app.VolunteerInfo', verbose_name='报名志愿者名单'),
        ),
        migrations.AddField(
            model_name='volserv',
            name='signup_user_list',
            field=models.ManyToManyField(blank=True, to='app.VolunteerInfo', verbose_name='报名志愿者名单'),
        ),
        migrations.AddField(
            model_name='proserv',
            name='proserv_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='微信用户'),
        ),
        migrations.AddField(
            model_name='policyqa',
            name='qa_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='微信用户'),
        ),
        migrations.AddField(
            model_name='charitycampaign',
            name='signup_user_list',
            field=models.ManyToManyField(blank=True, to='app.User', verbose_name='报名人员名单'),
        ),
    ]
