# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleuploadimg',
            options={'verbose_name_plural': '单图片上传'},
        ),
        migrations.RemoveField(
            model_name='charitycampaign',
            name='photos',
        ),
        migrations.AddField(
            model_name='charitycampaign',
            name='photos',
            field=models.ManyToManyField(blank=True, to='app.SingleUploadImg', verbose_name='活动图片'),
        ),
    ]
