# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180125_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleuploadimg',
            name='photo_name',
            field=models.CharField(default=0, max_length=10, verbose_name='照片名字'),
            preserve_default=False,
        ),
    ]
