# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_singleuploadimg_photo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('expire_in', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '核心token',
            },
        ),
    ]
