# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_access_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_refresh_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_subscribe_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='关注公众号时间'),
        ),
    ]
