# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180128_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
